### PR TITLE
Add metop

### PR DESCRIPTION
**Pull request by smacfarlane**
**Not ready for merge**

@spruceboy  I've had to refactor a bunch of the helper classes to minimize the amount of hoop-jumping needed to process MetOp.   I've also take the time to DRY up some of the code and pull all the common pieces back into the helpers.  The changes do break the existing scripts though.

I'm working through the existing scripts to match the changes I've made (separate branch),  but we won't want to merge into master until we've had a chance to test them all in staging.

### CODE REVIEW

**Comment by spruceboy** [comment]
Mostly looks ok, but some of the changes alter how the scripts are run -
why?  For examplethe -i/--input -o/--output stuff has changed to INPUT
OUTPUT on the command line, and the '-c'/'--config' stuff is gone, which is
sort of a bummer as its purpose was to allow testing with different config
files quickly.

Otherwise, looks great!



- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -

**Comment by smacfarlane** [comment]
The -c moved into ProcessingHelper::CommandLineHelper, although it's broken in this branch. I've got a fix in a different branch that needs to be pushed back up to this one. 

The input/output I moved to parameters rather than options as that seems to generally be considered 'best practice' for cli  --  command [-o options]  INPUT OUTPUT

**Comment by spruceboy** [comment]
Sure, but that is how the stuff was originally diagramed when it was layed
out on the white board last fall.  I don't have a problem with changing it,
I just think it should be dicussed before changing.

- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -

**Comment by smacfarlane** [comment]
That's my bad then, I don't remember diagramming down to the option level.  I'll revert the change to the input/ouput and we can discuss it offline.

**Comment by spruceboy** [comment]
There is no need to back it out - I am fine with the changes, I just would
prefer that changes that alter behavior or functionality get discussed
first.    We can count this a discussion, but it would make me much happier
to discuss before in the future.

The code structure changes are great.


- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -

**Pull request merged**
