### PR TITLE
Added in aqua files globs. 

### LINKED ISSUE #18: modis awips generation not saving files
@spruceboy 

It looks like the aqua processing isn't matching any files to copy to the cache.  Here's the gist of the latest run.  You can see it generate products successfully, but there are no messages about copying files, and the products list is empty.  

https://gist.github.com/smacfarlane/078820021dc5e764e5f8

### PR DESCRIPTION
**Pull request by spruceboy**
The globs could be all combined, but I was too lazy to figure out single glob that does both for both platforms.  This should work. 
Sorry I didn't notice this earlier! 

Closes #18

### CODE REVIEW

**Comment by spruceboy** [comment]
@smacfarlane is this ok?

**Comment by smacfarlane** [comment]
Were you able to confirm that that is what polar2grid spits out for aqua?  If so, then this looks good to go

**Comment by spruceboy** [comment]
Yup, just ran it on all the data l1 data currently available from the
dashboard.

- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -

**Comment by smacfarlane** [comment]
Great,  lets :shipit:

**Pull request merged**
